### ISSUE TITLE
我想用osgearth的最新版本去编译，确实不太容易啊，请问现在用哪个版本更好？

### ISSUE THREAD

**Issue by shaozhihua** [winrelde/myosgearth#1]
首先感谢作者的分享，osg库这两年更新不大，版本不多，osgearth却是从作者使用的2.10到了3.5吧好像是，很多API，确实改动不小，现在osgearth的改动不知道值不值的弄个最新的，去编译，所以想请教一下作者，是否有必要更新到最新版本的osgearth。。

**Comment by winrelde** [comment]
要不要更新我也不好说，很久没关注了，不知道3.0-3.5有什么新功能，不过你可以看看杨总的博客（https://blog.csdn.net/FreeSouthS/article/details/121093781?spm=1001.2014.3001.5501），里面有他编译好的库，还有一些学习资源，希望对你有帮助。

**Comment by shaozhihua** [comment]
好的，谢谢了。







| |
ryan_skys
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年4月17日 15:00 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [winrelde/OsgEarthQt] 我想用osgearth的最新版本去编译，确实不太容易啊，请问现在用哪个版本更好？ (Issue #1) |

要不要更新我也不好说，很久没关注了，不知道3.0-3.5有什么新功能，不过你可以看看杨总的博客（https://blog.csdn.net/FreeSouthS/article/details/121093781?spm=1001.2014.3001.5501），里面有他编译好的库，还有一些学习资源，希望对你有帮助。
